name: juce-plugin

on: workflow_dispatch

permissions:
  contents: write

jobs:

  juce-plugin:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Dev
        run: . .\devshell.ps1 && dev && write CMAKE-VERSION && cmake --version && write NINJA-VERSION && ninja --version && debug

      - name: Gui App Example
        uses: actions/upload-artifact@v3
        with:
          name: Gui App Example
          path: "build/GuiAppExample_artefacts/Debug/Gui App Example.exe"

      - name: Audio Plugin Example
        uses: actions/upload-artifact@v3
        with:
          name: Audio Plugin Example
          path: |
            "build/AudioPluginExample_artefacts/Debug/Standalone/Audio Plugin Example.exe"
            "build/AudioPluginExample_artefacts/Debug/VST3/Audio Plugin Example.vst3/"

      - name: Audio Plugin Host
        uses: actions/upload-artifact@v3
        with:
          name: Audio Plugin Host
          path: "build/AudioPluginHost_artefacts/Debug/AudioPluginHost.exe"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Gui App Example
          path: "build/GuiAppExample_artefacts/Debug/Gui App Example.exe"
