name: juce-plugin

on: workflow_dispatch

permissions:
  contents: write

jobs:

  juce-plugin:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Dev
        run: . .\devshell.ps1 && dev && write CMAKE-VERSION && cmake --version && write NINJA-VERSION && ninja --version && debug

      - name: Audio Plugin Example
        uses: actions/upload-artifact@v3
        with:
          name: Audio Plugin Example
          path: "build/AudioPluginExample_artefacts/Debug/Standalone/Audio Plugin Example.exe"
