name: juce-plugin

on: workflow_dispatch

permissions:
  contents: write

jobs:

  Juce-Plugin:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CMake
        run: . .\devshell.ps1 && dev && write CMAKE-VERSION && cmake --version && write NINJA-VERSION && ninja --version && debug

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Juce Plugin
          path: "build/JucePlugin_artefacts/Debug/Standalone/Juce Plugin.exe"
