name: Release Build - Ubuntu 64bit

on:
  push:
    tags: v**

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: PowerShell
        run: pwsh -NoExit -NonInteractive -File ".\scripts\Ubuntu.ps1"

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Juce Plugin
          path: "build/release/TestPlugin_artefacts/Release/Standalone/Test Plugin"
