name: Release Build - Ubuntu 64bit

on: workflow_dispatch

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: CMake
        run: sudo apt install ninja-build -y && Import-Module .\scripts\PowerShellScripts && release

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Juce Plugin
          path: "TestPlugin_artefacts/Release/Standalone/Test Plugin"
