name: Test

on: workflow_dispatch

permissions:
  contents: write

jobs:

  test:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: PowerShell
        run: New-Item -ItemType SymbolicLink -Path "C:\Users\runneradmin\Documents\PowerShell\Modules\PowerShellScripts" -Target "scripts\PowerShellScripts"

      - name: PowerShell
        run: 64bit
