name: Test

on: workflow_dispatch

permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: PowerShell
        run: pwsh -NoExit -NonInteractive -File ".\scripts\ubuntu.ps1"
