name: Test

on: workflow_dispatch

permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Dir
        run: mkdir test

      - name: PowerShell
        run: pwsh -NoExit -File ".\scripts\PowerShellScripts\PowerShellScripts.psm1" -Command {Get-ChildItem}
