name: test

on: workflow_dispatch

permissions:
  contents: write

jobs:

  test:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: PowerShell
        run: Import-Module .\scripts\PowerShellScripts && 64bit && plugin-release && ls && zip "Juce Plugin.zip" "build/JucePlugin_artefacts/Debug/Standalone/Juce Plugin.exe"
